In [9]:
import pandas as pd

In [10]:
data = pd.read_csv('players_22.csv')
display(data)

,overall,wage_eur,age,height_cm,weight_kg,league_level,club_position,club_contract_valid_until,nationality_id,nationality_name,...,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure
0,93,320000.0,34,170,72,1.0,RW,2023.0,52,Argentina,...,68,72,69,94,44,40,93,95,75,96
1,92,270000.0,32,185,81,1.0,ST,2023.0,37,Poland,...,85,76,86,87,81,49,95,81,90,88
2,91,270000.0,36,187,83,1.0,ST,2023.0,38,Portugal,...,95,77,77,93,63,29,95,76,88,95
3,91,270000.0,29,175,68,1.0,LW,2025.0,54,Brazil,...,64,81,53,81,63,37,86,90,93,93
4,91,350000.0,30,181,70,1.0,RCM,2025.0,7,Belgium,...,63,89,74,91,76,66,88,94,83,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,47,1000.0,22,180,64,1.0,SUB,2021.0,155,China PR,...,62,51,46,30,52,42,38,43,42,37
19235,47,500.0,19,175,70,1.0,RES,2021.0,25,Republic of Ireland,...,47,63,47,38,49,39,51,49,44,47
19236,47,500.0,21,178,72,1.0,RES,2021.0,25,Republic of Ireland,...,57,56,50,34,51,38,45,46,39,36
19237,47,500.0,19,173,66,1.0,RES,2021.0,25,Republic of Ireland,...,50,50,40,41,34,14,47,40,49,47
19238,47,500.0,19,167,61,1.0,SUB,2025.0,159,India,...,62,57,40,36,55,42,47,46,35,36

In [11]:
#display(data.loc[data["Wage"]== '0'])

In [16]:
df = data.loc[:, (data != '0').all(axis=0)].dropna()
display(df)

,overall,wage_eur,age,height_cm,weight_kg,league_level,club_position,club_contract_valid_until,nationality_id,nationality_name,...,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure
0,93,320000.0,34,170,72,1.0,RW,2023.0,52,Argentina,...,68,72,69,94,44,40,93,95,75,96
1,92,270000.0,32,185,81,1.0,ST,2023.0,37,Poland,...,85,76,86,87,81,49,95,81,90,88
2,91,270000.0,36,187,83,1.0,ST,2023.0,38,Portugal,...,95,77,77,93,63,29,95,76,88,95
3,91,270000.0,29,175,68,1.0,LW,2025.0,54,Brazil,...,64,81,53,81,63,37,86,90,93,93
4,91,350000.0,30,181,70,1.0,RCM,2025.0,7,Belgium,...,63,89,74,91,76,66,88,94,83,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,47,1000.0,22,180,64,1.0,SUB,2021.0,155,China PR,...,62,51,46,30,52,42,38,43,42,37
19235,47,500.0,19,175,70,1.0,RES,2021.0,25,Republic of Ireland,...,47,63,47,38,49,39,51,49,44,47
19236,47,500.0,21,178,72,1.0,RES,2021.0,25,Republic of Ireland,...,57,56,50,34,51,38,45,46,39,36
19237,47,500.0,19,173,66,1.0,RES,2021.0,25,Republic of Ireland,...,50,50,40,41,34,14,47,40,49,47
19238,47,500.0,19,167,61,1.0,SUB,2025.0,159,India,...,62,57,40,36,55,42,47,46,35,36

In [17]:
#final_data = df.iloc[:600]
final_data = df[['age','overall','wage_eur','height_cm','weight_kg','pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_heading_accuracy', 'attacking_short_passing', 'skill_dribbling', 'skill_curve', 'power_shot_power', 'power_jumping', 'mentality_aggression', 'mentality_interceptions', 'mentality_vision', 'mentality_penalties']]

In [18]:
display(final_data)

,age,overall,wage_eur,height_cm,weight_kg,pace,shooting,passing,dribbling,defending,...,power_shot_power,power_jumping,mentality_aggression,mentality_interceptions,mentality_vision,mentality_penalties,league_level,nationality_name,club_contract_valid_until,work_rate
0,34,93,320000.0,170,72,85.0,92.0,91.0,95.0,34.0,...,86,68,44,40,95,75,1.0,Argentina,2023.0,Medium/Low
1,32,92,270000.0,185,81,78.0,92.0,79.0,86.0,44.0,...,90,85,81,49,81,90,1.0,Poland,2023.0,High/Medium
2,36,91,270000.0,187,83,87.0,94.0,80.0,88.0,34.0,...,94,95,63,29,76,88,1.0,Portugal,2023.0,High/Low
3,29,91,270000.0,175,68,91.0,83.0,86.0,94.0,37.0,...,80,64,63,37,90,93,1.0,Brazil,2025.0,High/Medium
4,30,91,350000.0,181,70,76.0,86.0,93.0,88.0,64.0,...,91,63,76,66,94,83,1.0,Belgium,2025.0,High/High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,22,47,1000.0,180,64,58.0,35.0,46.0,48.0,42.0,...,46,62,52,42,43,42,1.0,China PR,2021.0,Medium/Medium
19235,19,47,500.0,175,70,59.0,39.0,50.0,46.0,41.0,...,49,47,49,39,49,44,1.0,Republic of Ireland,2021.0,Medium/Medium
19236,21,47,500.0,178,72,60.0,37.0,45.0,49.0,41.0,...,50,57,51,38,46,39,1.0,Republic of Ireland,2021.0,Medium/Medium
19237,19,47,500.0,173,66,68.0,46.0,36.0,48.0,15.0,...,48,50,34,14,40,49,1.0,Republic of Ireland,2021.0,Medium/Medium
19238,19,47,500.0,167,61,68.0,38.0,45.0,48.0,36.0,...,50,62,55,42,46,35,1.0,India,2025.0,Medium/Medium

In [21]:
options = ['Argentina', 'Brazil', 'Germany', 'Portugal', 'Spain', 'France', 'Netherlands', 'England', 'Belgium', 'Italy']
rslt_df = final_data[final_data['nationality_name'].isin(options)]  
display(rslt_df)

,age,overall,wage_eur,height_cm,weight_kg,pace,shooting,passing,dribbling,defending,...,power_shot_power,power_jumping,mentality_aggression,mentality_interceptions,mentality_vision,mentality_penalties,league_level,nationality_name,club_contract_valid_until,work_rate
0,34,93,320000.0,170,72,85.0,92.0,91.0,95.0,34.0,...,86,68,44,40,95,75,1.0,Argentina,2023.0,Medium/Low
2,36,91,270000.0,187,83,87.0,94.0,80.0,88.0,34.0,...,94,95,63,29,76,88,1.0,Portugal,2023.0,High/Low
3,29,91,270000.0,175,68,91.0,83.0,86.0,94.0,37.0,...,80,64,63,37,90,93,1.0,Brazil,2025.0,High/Medium
4,30,91,350000.0,181,70,76.0,86.0,93.0,88.0,64.0,...,91,63,76,66,94,83,1.0,Belgium,2025.0,High/High
6,22,91,230000.0,182,73,97.0,88.0,80.0,92.0,36.0,...,86,78,62,38,82,79,1.0,France,2022.0,High/Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19082,18,50,650.0,175,70,71.0,48.0,46.0,50.0,33.0,...,47,55,38,36,43,51,4.0,England,2022.0,Medium/Medium
19083,19,50,2000.0,186,64,64.0,39.0,50.0,48.0,43.0,...,55,58,51,42,46,43,2.0,England,2023.0,Medium/Medium
19098,17,50,500.0,175,64,73.0,50.0,37.0,51.0,15.0,...,49,55,30,14,44,59,4.0,England,2022.0,Medium/Medium
19099,20,50,2000.0,175,64,64.0,44.0,50.0,54.0,41.0,...,47,50,41,43,52,46,4.0,England,2022.0,Medium/Medium
19169,17,49,500.0,171,68,61.0,35.0,52.0,49.0,33.0,...,40,52,40,21,57,47,1.0,Brazil,2023.0,Medium/Medium

In [22]:
n = rslt_df.nunique(axis=0)
print(n)

age                            26
overall                        44
wage_eur                      132
height_cm                      46
weight_kg                      49
pace                           69
shooting                       74
passing                        65
dribbling                      66
defending                      76
physic                         60
attacking_crossing             78
attacking_heading_accuracy     76
attacking_short_passing        67
skill_dribbling                78
skill_curve                    78
power_shot_power               75
power_jumping                  67
mentality_aggression           76
mentality_interceptions        82
mentality_vision               79
mentality_penalties            78
league_level                    5
nationality_name               10
club_contract_valid_until       9
work_rate                       9
dtype: int64

In [23]:
rslt_df = rslt_df.sample(n=550)
display(rslt_df)

,age,overall,wage_eur,height_cm,weight_kg,pace,shooting,passing,dribbling,defending,...,power_shot_power,power_jumping,mentality_aggression,mentality_interceptions,mentality_vision,mentality_penalties,league_level,nationality_name,club_contract_valid_until,work_rate
13744,21,62,2000.0,175,70,74.0,35.0,49.0,63.0,58.0,...,37,64,54,59,45,43,2.0,England,2023.0,Medium/Medium
12454,26,63,9000.0,181,70,61.0,48.0,61.0,64.0,64.0,...,48,60,55,62,57,52,1.0,England,2022.0,Medium/Medium
3968,32,71,10000.0,184,77,70.0,70.0,75.0,71.0,42.0,...,80,64,51,46,76,79,2.0,Germany,2023.0,Medium/Medium
13867,20,62,1000.0,179,71,73.0,53.0,60.0,69.0,31.0,...,56,62,47,27,59,49,3.0,Germany,2024.0,Medium/Medium
4092,26,71,6000.0,187,80,80.0,65.0,61.0,66.0,67.0,...,80,81,62,70,48,45,2.0,Spain,2022.0,High/Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15120,21,61,2000.0,177,70,63.0,50.0,58.0,62.0,56.0,...,66,57,64,50,51,54,1.0,Argentina,2023.0,Medium/Medium
5262,22,70,11000.0,184,83,68.0,38.0,59.0,63.0,70.0,...,47,70,70,67,55,37,1.0,France,2025.0,Medium/Medium
16447,19,59,1000.0,180,70,61.0,43.0,58.0,61.0,55.0,...,60,59,61,56,52,51,1.0,Argentina,2024.0,Medium/Medium
13268,23,63,500.0,170,67,67.0,62.0,57.0,69.0,27.0,...,55,49,26,32,54,56,1.0,Brazil,2021.0,Medium/Low
17550,20,56,2000.0,185,73,80.0,54.0,46.0,57.0,20.0,...,52,68,31,13,51,58,3.0,England,2022.0,Medium/Medium

In [27]:
rslt_df.to_csv('final_data.csv')

In [25]:
print(rslt_df.nunique(axis=0))

age                           23
overall                       35
wage_eur                      73
height_cm                     35
weight_kg                     37
pace                          59
shooting                      60
passing                       55
dribbling                     52
defending                     64
physic                        48
attacking_crossing            65
attacking_heading_accuracy    55
attacking_short_passing       51
skill_dribbling               59
skill_curve                   68
power_shot_power              64
power_jumping                 55
mentality_aggression          64
mentality_interceptions       71
mentality_vision              60
mentality_penalties           60
league_level                   5
nationality_name              10
club_contract_valid_until      6
work_rate                      9
dtype: int64